# ~/.config/starship.toml

add_newline = true

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = true # Desactiva mostrar la versiÃ³n del package.json siempre (reduce ruido)

[nodejs]
symbol = "â¬¢ "
style = "bold green"

[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_status]
style = "red"
deleted = "x"

[directory]
truncation_length = 3
style = "bold blue"
read_only = " ğŸ”’"

[docker_context]
symbol = "ïŒˆ "
style = "blue dimmed"

# EstÃ©tica general
format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$docker_context\
\n$character"""